version: '2.2'

services:
  db:
    image: postgres:9.6.15-alpine
    restart: always
    env_file:
      - ./config/.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  reflected-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    stdin_open: true
    tty: true
    env_file:
      - ./config/.env
    command: >
      sh -c "python --version
      && sleep 10
      && python src/manage.py makemigrations
      && python src/manage.py makemigrations api
      && python src/manage.py migrate
      && python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
